# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from tank.platform.qt import QtCore, QtGui

class DraggableTableWidget(QtGui.QTableWidget):
    def __init__(self, parent=None):
        super(DraggableTableWidget, self).__init__(parent)
        #TODO: Implement drag and drop functionality
        #self.setDragEnabled(True)
        #self.setAcceptDrops(True)
        #self.setDragDropMode(QtGui.QTableWidget.InternalMove)
        self.setSelectionBehavior(QtGui.QTableWidget.SelectRows)
        self.setSelectionMode(QtGui.QTableWidget.MultiSelection)

    def dropEvent(self, event):
        source_row = self.currentRow()
        target_row = self.rowAt(event.pos().y())

        if target_row == -1:
            target_row = self.rowCount() - 1

        if source_row != target_row:
            self.insertRow(target_row)
            for column in range(self.columnCount()):
                self.setItem(target_row, column, self.takeItem(source_row, column))
            self.removeRow(source_row)

        event.accept()

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        Dialog.setMinimumSize(QtCore.QSize(800, 600))
        self.horizontalLayout = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.mainLayout = QtGui.QVBoxLayout()
        self.mainLayout.setObjectName("mainLayout")

        # Comp Table
        self.compTableHeaders = ["Comp Name", "Status", "Frame Range", "Frame Output", "Render Template", "Use Comp Name", "Include"]

        self.compTableWidget = DraggableTableWidget(Dialog)
        self.compTableWidget.setObjectName("compTableWidget")
        self.compTableWidget.setColumnCount(len(self.compTableHeaders))
        self.compTableWidget.setHorizontalHeaderLabels(self.compTableHeaders)

        # Set column resize mode
        header = self.compTableWidget.horizontalHeader()
        header.setSectionResizeMode(0, QtGui.QHeaderView.Stretch)
        header.setSectionResizeMode(1, QtGui.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtGui.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(3, QtGui.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(4, QtGui.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(5, QtGui.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(6, QtGui.QHeaderView.ResizeToContents)

        self.mainLayout.addWidget(self.compTableWidget)

        # Buttons
        self.buttonsLayout = QtGui.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")

        # Add Selected To Queue
        self.addButton = QtGui.QPushButton(Dialog)
        self.addButton.setObjectName("addButton")
        self.addButton.setText("Add To Queue")
        self.addButton.setMinimumHeight(30)

        # Apply To Render Queue
        self.applyButton = QtGui.QPushButton(Dialog)
        self.applyButton.setObjectName("applyButton")
        self.applyButton.setText("Apply")
        self.applyButton.setMinimumHeight(30)

        # Refresh Comp List
        self.refreshButton = QtGui.QPushButton(Dialog)
        self.refreshButton.setObjectName("refreshButton")
        self.refreshButton.setText("Refresh Comp List")
        self.refreshButton.setMinimumHeight(30)

        # Cancel
        self.cancelButton = QtGui.QPushButton(Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.cancelButton.setText("Cancel")
        self.cancelButton.setMinimumHeight(30)

        self.buttonsLayout.addWidget(self.addButton)
        self.buttonsLayout.addWidget(self.refreshButton)
        self.buttonsLayout.addWidget(self.applyButton)
        self.buttonsLayout.addWidget(self.cancelButton)

        self.mainLayout.addLayout(self.buttonsLayout)
        self.horizontalLayout.addLayout(self.mainLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Selected Comps to Render Queue"))
        self.addButton.setText(_translate("Dialog", "Add To Queue"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
from . import resources_rc
