# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from tank.platform.qt import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(395, 298)

        self.horizontalLayout = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainLayout = QtGui.QVBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.frameRangeGroupBox = QtGui.QGroupBox(Dialog)
        self.frameRangeGroupBox.setObjectName("frameRangeGroupBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frameRangeGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameRangeLineEdit = QtGui.QLineEdit(self.frameRangeGroupBox)
        self.frameRangeLineEdit.setObjectName("frameRangeLineEdit")
        self.horizontalLayout_2.addWidget(self.frameRangeLineEdit)
        self.frameRangeComboBox = QtGui.QComboBox(self.frameRangeGroupBox)
        self.frameRangeComboBox.setObjectName("frameRangeComboBox")
        self.horizontalLayout_2.addWidget(self.frameRangeComboBox)
        self.mainLayout.addWidget(self.frameRangeGroupBox)
        self.renderFormatLayout = QtGui.QGroupBox(Dialog)
        self.renderFormatLayout.setObjectName("renderFormatLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.renderFormatLayout)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.renderFormatDropdown = QtGui.QComboBox(self.renderFormatLayout)
        self.renderFormatDropdown.setObjectName("renderFormatDropdown")
        self.verticalLayout_2.addWidget(self.renderFormatDropdown)
        self.mainLayout.addWidget(self.renderFormatLayout)

        # Options
        self.optionsLayout = QtGui.QHBoxLayout()
        self.optionsLayout.setObjectName("optionsLayout")
        self.optionsGroupBox = QtGui.QGroupBox(Dialog)
        self.optionsGroupBox.setObjectName("optionsGroupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.optionsGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.useCompNameCheckBox = QtGui.QCheckBox(self.optionsGroupBox)
        self.useCompNameCheckBox.setObjectName("useCompNameCheckBox")
        self.useCompNameCheckBox.setChecked(True)
        self.verticalLayout.addWidget(self.useCompNameCheckBox)
        self.optionsLayout.addWidget(self.optionsGroupBox)
        self.mainLayout.addLayout(self.optionsLayout)

        # Buttons
        self.buttonsLayout = QtGui.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.addButton = QtGui.QPushButton(Dialog)
        self.addButton.setObjectName("addButton")
        self.buttonsLayout.addWidget(self.addButton)
        self.cancelButton = QtGui.QPushButton(Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonsLayout.addWidget(self.cancelButton)
        self.mainLayout.addLayout(self.buttonsLayout)
        self.horizontalLayout.addLayout(self.mainLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Comps to Render Queue"))
        self.frameRangeGroupBox.setTitle(_translate("Dialog", "Frame Range"))
        self.frameRangeLineEdit.setPlaceholderText(_translate("Dialog", "1001-1100"))
        self.renderFormatLayout.setTitle(_translate("Dialog", "Render Format"))
        self.addButton.setText(_translate("Dialog", "Add To Queue"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.optionsGroupBox.setTitle(_translate("Dialog", "Options"))
        self.useCompNameCheckBox.setText(_translate("Dialog", "Use Comp Name as Render Name"))
from . import resources_rc
